source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

$menu_font_size = 24

# 󰍃  Logout
# 󰜉  Restart
# 󰐥  Shutdown
#   Boot to Windows

# label {
#     monitor =
#     text = 󰍃  Logout
#
#     position = -40%, -45%
#
#     inner_color = $inner_color
#     outer_color = $outer_color
#     outline_thickness = 0
#
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color
#     font_size = $menu_font_size
# }
#
# label {
#     monitor =
#     text = 󰜉  Restart
#
#     position = -25%, -45%
#
#     inner_color = $inner_color
#     outer_color = $outer_color
#     outline_thickness = 0
#
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color
#     font_size = $menu_font_size
# }
#
# label {
#     monitor =
#     text = 󰐥  Shutdown
#
#     position = -10%, -45%
#
#     inner_color = $inner_color
#     outer_color = $outer_color
#     outline_thickness = 0
#
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color
#     font_size = $menu_font_size
# }
#
# label {
#     monitor =
#     text =   Boot to Windows
#
#     position = 10%, -45%
#
#     inner_color = $inner_color
#     outer_color = $outer_color
#     outline_thickness = 0
#
#     font_family = CaskaydiaMono Nerd Font
#     font_color = $font_color
#     font_size = $menu_font_size
# }

label {
    monitor =
    text = $TIME12

    position = 0, 15%

    font_family = CaskaydiaMono Nerd Font
    font_color = $outer_color
    font_size = 180
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d %Y')"

    position = 0, 0%

    font_family = CaskaydiaMono Nerd Font
    font_color = $outer_color
    font_size = 24
}


input-field {
    monitor =
    size = 650, 100
    position = 0, -15%
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 0

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 24
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
