# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0
    # Use master layout instead of dwindle
}

source = animation.conf

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
    dim_inactive = false
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

windowrule {
  name = spotify-rules
  match:initial_class = Spotify
  float = true
  size = (monitor_w*0.8) (monitor_h*0.8)
  # stay_focused = true
  center = true
  # no_screen_share = true
  immediate = true
}
windowrule {
  name = rambox-rules
  match:initial_class = rambox
  float = true
  size = (monitor_w*0.8) (monitor_h*0.8)
  # stay_focused = true
  center = true
  # no_screen_share = true
  immediate = true
}

windowrule {
  name = spf
  match:initial_class = TUI.superfile
  float = true
  size = (monitor_w*0.7) (monitor_h*0.9)
  # stay_focused = true
  center = true
  # no_screen_share = true
  immediate = true
}

windowrule {
  name = neovide-rules
  match:initial_class = neovide
  # float = true
  # size = (monitor_w*0.8) (monitor_h*0.8)
  # stay_focused = true
  # center = true
  # no_screen_share = true
  # immediate = true
  opacity = 0.5
}
windowrule {
  name = file-upload
  match:initial_title = .*File Upload.*
  float = true
  size = (monitor_w*0.7) (monitor_h*0.9)
  center = true
  immediate = true
}

windowrule = match:initial_class gcr-prompter, stay_focused true
windowrule = match:initial_class jetbrains-toolbox, center true, float true
