general {
    layout = scrolling
}
scrolling {
  focus_fit_method = 1
  follow_focus = false
  follow_min_visible = 0.5
  fullscreen_on_one_column = false
}
unbind = SUPER_CTRL, left
unbind = SUPER_CTRL, right

bind = SUPER_CTRL, left, layoutmsg, colresize -0.125
bind = SUPER_CTRL, right, layoutmsg, colresize +0.125

# windowrule {
#   name = floating-scrolling
#   match:float = true
#   pin = on
# }


